const copy = {
  fr: {navGames:"Nos jeux",navStudio:"Le studio",navContact:"Contact",heroKicker:"STUDIO INDÉPENDANT · FRANCE",heroTitle:"Des jeux mobiles<br>qui vont droit au <em>jeu.</em>",heroText:"PixelRed Studio imagine des expériences mobiles immédiates, exigeantes et faciles à reprendre. Deux univers, deux façons de tester ses réflexes.",heroPrimary:"Découvrir nos jeux",heroSecondary:"Jouer à TapSafe",heroNote:"Des jeux conçus et développés avec soin.",scroll:"Défiler",gamesKicker:"LE CATALOGUE",gamesTitle:"Deux jeux. Une seule envie :<br>recommencer.",gamesText:"Des règles simples à comprendre, un vrai défi à maîtriser.",tapStatus:"DISPONIBLE SUR GOOGLE PLAY",tapDesc:"Touchez les bonnes couleurs, évitez celle qui est interdite. Un jeu d’arcade de réflexes avec missions quotidiennes, bonus et éléments cosmétiques à débloquer.",tapCta:"Télécharger sur Google Play",flickStatus:"BÊTA FERMÉE",flickDesc:"Observez les cases qui s’allument, mémorisez leur ordre et reproduisez le signal avant la fin du chrono. Un défi quotidien est commun à tous.",flickCta:"Découvrir la bêta Flickerun",studioKicker:"PIXELRED STUDIO",studioTitle:"Petit studio.<br>Jeux faits pour durer.",studioText:"Nous créons des jeux mobiles indépendants autour de mécaniques lisibles, d’une direction artistique affirmée et d’une progression qui respecte le joueur.",studioCta:"Parlons de jeux",studioAside:"Réflexes, mémoire et une nouvelle partie à portée de main.",footerPrivacy:"Confidentialité",footerLegal:"Mentions légales"},
  en: {navGames:"Games",navStudio:"Studio",navContact:"Contact",heroKicker:"INDEPENDENT STUDIO · FRANCE",heroTitle:"Mobile games<br>that get straight to <em>play.</em>",heroText:"PixelRed Studio builds immediate, demanding mobile experiences that are easy to pick up again. Two worlds, two ways to test your reflexes.",heroPrimary:"Explore our games",heroSecondary:"Play TapSafe",heroNote:"Games designed and developed with care.",scroll:"Scroll",gamesKicker:"THE LINEUP",gamesTitle:"Two games. One reason<br>to play again.",gamesText:"Easy to understand. A real challenge to master.",tapStatus:"AVAILABLE ON GOOGLE PLAY",tapDesc:"Tap the right colors and avoid the forbidden one. A reflex arcade game with daily missions, power-ups and unlockable cosmetics.",tapCta:"Get it on Google Play",flickStatus:"CLOSED BETA",flickDesc:"Watch the tiles light up, memorize their order and repeat the signal before time runs out. Everyone gets the same daily challenge.",flickCta:"Explore the Flickerun beta",studioKicker:"PIXELRED STUDIO",studioTitle:"A small studio.<br>Games made to last.",studioText:"We make independent mobile games with clear mechanics, a distinct visual identity and progression designed around the player.",studioCta:"Talk games with us",studioAside:"Reflexes, memory and another round within reach.",footerPrivacy:"Privacy",footerLegal:"Legal notice"},
  de: {navGames:"Spiele",navStudio:"Studio",navContact:"Kontakt",heroKicker:"UNABHÄNGIGES STUDIO · FRANKREICH",heroTitle:"Mobile Spiele,<br>die direkt zum <em>Spiel</em> kommen.",heroText:"PixelRed Studio entwickelt unmittelbare, anspruchsvolle Mobile-Erlebnisse, zu denen man gern zurückkehrt. Zwei Welten, zwei Arten, deine Reflexe zu testen.",heroPrimary:"Unsere Spiele",heroSecondary:"TapSafe spielen",heroNote:"Mit Sorgfalt entwickelte Spiele.",scroll:"Scrollen",gamesKicker:"DAS SPIELEPORTFOLIO",gamesTitle:"Zwei Spiele. Ein Grund,<br>weiterzuspielen.",gamesText:"Leicht zu verstehen. Eine echte Herausforderung.",tapStatus:"JETZT BEI GOOGLE PLAY",tapDesc:"Tippe die richtigen Farben an und meide die verbotene. Ein Reflex-Arcade-Spiel mit täglichen Missionen, Boosts und freischaltbaren Designs.",tapCta:"Bei Google Play laden",flickStatus:"GESCHLOSSENE BETA",flickDesc:"Merke dir die aufleuchtenden Felder und wiederhole das Signal rechtzeitig. Die tägliche Herausforderung ist für alle gleich.",flickCta:"Flickerun-Beta ansehen",studioKicker:"PIXELRED STUDIO",studioTitle:"Kleines Studio.<br>Spiele mit Ausdauer.",studioText:"Wir entwickeln unabhängige Mobile-Spiele mit klaren Regeln, eigenständigem Design und Fortschritt, der Spieler respektiert.",studioCta:"Über Spiele sprechen",studioAside:"Reflexe, Gedächtnis und eine neue Runde ganz nah.",footerPrivacy:"Datenschutz",footerLegal:"Impressum"},
  es: {navGames:"Juegos",navStudio:"Estudio",navContact:"Contacto",heroKicker:"ESTUDIO INDEPENDIENTE · FRANCIA",heroTitle:"Juegos móviles<br>que van directos al <em>juego.</em>",heroText:"PixelRed Studio crea experiencias móviles inmediatas, exigentes y fáciles de retomar. Dos mundos, dos formas de poner a prueba tus reflejos.",heroPrimary:"Descubre nuestros juegos",heroSecondary:"Jugar a TapSafe",heroNote:"Juegos diseñados y desarrollados con cuidado.",scroll:"Desplazar",gamesKicker:"EL CATÁLOGO",gamesTitle:"Dos juegos. Un motivo<br>para volver a jugar.",gamesText:"Fáciles de entender. Un reto de verdad.",tapStatus:"DISPONIBLE EN GOOGLE PLAY",tapDesc:"Toca los colores correctos y evita el prohibido. Un juego arcade de reflejos con misiones diarias, potenciadores y diseños desbloqueables.",tapCta:"Descargar en Google Play",flickStatus:"BETA CERRADA",flickDesc:"Observa las casillas iluminadas, memoriza el orden y repite la señal antes de que termine el tiempo. El reto diario es igual para todos.",flickCta:"Ver la beta de Flickerun",studioKicker:"PIXELRED STUDIO",studioTitle:"Un estudio pequeño.<br>Juegos que perduran.",studioText:"Creamos juegos móviles independientes con mecánicas claras, identidad visual propia y una progresión que respeta al jugador.",studioCta:"Hablemos de juegos",studioAside:"Reflejos, memoria y otra partida al alcance.",footerPrivacy:"Privacidad",footerLegal:"Aviso legal"},
  it: {navGames:"Giochi",navStudio:"Studio",navContact:"Contatti",heroKicker:"STUDIO INDIPENDENTE · FRANCIA",heroTitle:"Giochi mobile<br>che vanno dritti al <em>gioco.</em>",heroText:"PixelRed Studio crea esperienze mobile immediate, impegnative e facili da riprendere. Due mondi, due modi per mettere alla prova i tuoi riflessi.",heroPrimary:"Scopri i giochi",heroSecondary:"Gioca a TapSafe",heroNote:"Giochi progettati e sviluppati con cura.",scroll:"Scorri",gamesKicker:"IL CATALOGO",gamesTitle:"Due giochi. Un motivo<br>per riprovare.",gamesText:"Facili da capire. Una vera sfida da padroneggiare.",tapStatus:"DISPONIBILE SU GOOGLE PLAY",tapDesc:"Tocca i colori giusti ed evita quello vietato. Un gioco arcade di riflessi con missioni giornaliere, potenziamenti ed elementi estetici da sbloccare.",tapCta:"Scarica su Google Play",flickStatus:"BETA CHIUSA",flickDesc:"Osserva le caselle che si illuminano, memorizza l’ordine e ripeti il segnale prima che scada il tempo. La sfida quotidiana è uguale per tutti.",flickCta:"Scopri la beta Flickerun",studioKicker:"PIXELRED STUDIO",studioTitle:"Un piccolo studio.<br>Giochi che durano.",studioText:"Creiamo giochi mobile indipendenti con meccaniche chiare, un’identità visiva distintiva e progressi pensati per i giocatori.",studioCta:"Parliamo di giochi",studioAside:"Riflessi, memoria e una nuova partita a portata di mano.",footerPrivacy:"Privacy",footerLegal:"Note legali"},
  pt: {navGames:"Jogos",navStudio:"Estúdio",navContact:"Contacto",heroKicker:"ESTÚDIO INDEPENDENTE · FRANÇA",heroTitle:"Jogos para telemóvel<br>que vão direto ao <em>jogo.</em>",heroText:"A PixelRed Studio cria experiências móveis imediatas, exigentes e fáceis de retomar. Dois universos, duas formas de testar os teus reflexos.",heroPrimary:"Descobrir jogos",heroSecondary:"Jogar TapSafe",heroNote:"Jogos concebidos e desenvolvidos com cuidado.",scroll:"Deslizar",gamesKicker:"O CATÁLOGO",gamesTitle:"Dois jogos. Um motivo<br>para voltar a jogar.",gamesText:"Fáceis de perceber. Um verdadeiro desafio.",tapStatus:"DISPONÍVEL NO GOOGLE PLAY",tapDesc:"Toca nas cores certas e evita a proibida. Um jogo arcade de reflexos com missões diárias, poderes e visuais para desbloquear.",tapCta:"Transferir no Google Play",flickStatus:"BETA FECHADA",flickDesc:"Observa as casas iluminadas, memoriza a ordem e repete o sinal antes do tempo acabar. O desafio diário é igual para todos.",flickCta:"Conhecer a beta Flickerun",studioKicker:"PIXELRED STUDIO",studioTitle:"Um pequeno estúdio.<br>Jogos para durar.",studioText:"Criamos jogos móveis independentes com mecânicas claras, identidade visual própria e progressão pensada para respeitar o jogador.",studioCta:"Vamos falar de jogos",studioAside:"Reflexos, memória e mais uma partida à distância de um toque.",footerPrivacy:"Privacidade",footerLegal:"Aviso legal"},
  ru: {navGames:"Игры",navStudio:"Студия",navContact:"Контакты",heroKicker:"НЕЗАВИСИМАЯ СТУДИЯ · ФРАНЦИЯ",heroTitle:"Мобильные игры,<br>сразу переходящие к <em>делу.</em>",heroText:"PixelRed Studio создаёт динамичные и сложные мобильные игры, к которым легко вернуться. Два мира — два способа проверить реакцию.",heroPrimary:"Наши игры",heroSecondary:"Играть в TapSafe",heroNote:"Игры, созданные с вниманием к деталям.",scroll:"Прокрутить",gamesKicker:"НАШИ ИГРЫ",gamesTitle:"Две игры. Один повод<br>сыграть ещё раз.",gamesText:"Правила просты. Испытание настоящее.",tapStatus:"ДОСТУПНО В GOOGLE PLAY",tapDesc:"Нажимайте на нужные цвета и избегайте запрещённого. Аркадная игра на реакцию с ежедневными заданиями, усилениями и открываемыми оформлениями.",tapCta:"Скачать в Google Play",flickStatus:"ЗАКРЫТАЯ БЕТА",flickDesc:"Запоминайте порядок вспыхивающих клеток и повторяйте сигнал до истечения времени. Ежедневное испытание одинаково для всех.",flickCta:"О бета-тесте Flickerun",studioKicker:"PIXELRED STUDIO",studioTitle:"Небольшая студия.<br>Игры надолго.",studioText:"Мы создаём независимые мобильные игры с понятными правилами, ярким стилем и прогрессом, который уважает игрока.",studioCta:"Обсудить игры",studioAside:"Реакция, память и новый раунд под рукой.",footerPrivacy:"Конфиденциальность",footerLegal:"Правовая информация"},
  ja: {navGames:"ゲーム",navStudio:"スタジオ",navContact:"お問い合わせ",heroKicker:"フランスのインディースタジオ",heroTitle:"すぐに遊べる<br>モバイルゲームを。",heroText:"PixelRed Studioは、すぐ始められて何度も遊びたくなる、歯ごたえのあるモバイル体験を制作しています。2つの世界で反射神経を試そう。",heroPrimary:"ゲームを見る",heroSecondary:"TapSafeを遊ぶ",heroNote:"丁寧に設計・開発したゲーム。",scroll:"スクロール",gamesKicker:"ゲームラインナップ",gamesTitle:"2つのゲーム。<br>もう一度遊ぶ理由。",gamesText:"ルールは簡単。攻略は本格的。",tapStatus:"Google Playで配信中",tapDesc:"正しい色をタップし、禁止色を避けよう。毎日のミッション、パワーアップ、アンロックできるスキンがある反射神経アーケードゲーム。",tapCta:"Google Playで入手",flickStatus:"クローズドベータ",flickDesc:"光るマスの順番を覚え、時間内に同じ順番でタップしよう。毎日、全員共通のチャレンジに挑戦できます。",flickCta:"Flickerunベータを見る",studioKicker:"PIXELRED STUDIO",studioTitle:"小さなスタジオ。<br>長く遊べるゲーム。",studioText:"明快なルール、独自のビジュアル、プレイヤーを大切にした成長要素を備えるインディーモバイルゲームを制作します。",studioCta:"ゲームについて話す",studioAside:"反射神経、記憶力、そしてすぐに次の一戦へ。",footerPrivacy:"プライバシー",footerLegal:"法的情報"},
  ko: {navGames:"게임",navStudio:"스튜디오",navContact:"문의",heroKicker:"프랑스 인디 게임 스튜디오",heroTitle:"바로 플레이하는<br>모바일 게임.",heroText:"PixelRed Studio는 바로 시작할 수 있고 다시 찾게 되는 도전적인 모바일 경험을 만듭니다. 두 가지 세계에서 반사 신경을 시험해 보세요.",heroPrimary:"게임 둘러보기",heroSecondary:"TapSafe 플레이",heroNote:"세심하게 기획하고 개발한 게임.",scroll:"스크롤",gamesKicker:"게임 라인업",gamesTitle:"두 게임. 다시 플레이할<br>하나의 이유.",gamesText:"규칙은 쉽고, 도전은 확실합니다.",tapStatus:"GOOGLE PLAY에서 이용 가능",tapDesc:"맞는 색을 누르고 금지된 색은 피하세요. 일일 미션, 파워업, 잠금 해제 가능한 꾸미기 요소를 갖춘 반사 신경 아케이드 게임입니다.",tapCta:"Google Play에서 받기",flickStatus:"비공개 베타",flickDesc:"불이 켜진 타일 순서를 기억하고 시간 안에 다시 입력하세요. 매일 모두에게 같은 도전이 제공됩니다.",flickCta:"Flickerun 베타 보기",studioKicker:"PIXELRED STUDIO",studioTitle:"작은 스튜디오.<br>오래 즐기는 게임.",studioText:"명확한 규칙, 뚜렷한 비주얼, 플레이어를 존중하는 성장을 갖춘 인디 모바일 게임을 만듭니다.",studioCta:"게임 이야기 나누기",studioAside:"반사 신경과 기억력, 그리고 손끝에서 시작하는 다음 라운드.",footerPrivacy:"개인정보 보호",footerLegal:"법적 고지"},
  zh: {navGames:"游戏",navStudio:"工作室",navContact:"联系",heroKicker:"法国独立游戏工作室",heroTitle:"即刻上手的<br>移动游戏。",heroText:"PixelRed Studio打造节奏直接、富有挑战且让人想再次游玩的移动体验。两个世界，两种反应力挑战。",heroPrimary:"探索游戏",heroSecondary:"游玩 TapSafe",heroNote:"用心设计与开发的游戏。",scroll:"向下滚动",gamesKicker:"游戏阵容",gamesTitle:"两款游戏。<br>再来一局的理由。",gamesText:"规则易懂，挑战十足。",tapStatus:"已在 Google Play 上架",tapDesc:"点击正确的颜色，避开禁色。这是一款考验反应力的街机游戏，包含每日任务、强化道具和可解锁外观。",tapCta:"前往 Google Play 下载",flickStatus:"封闭测试版",flickDesc:"记住亮起方块的顺序，并在倒计时结束前复现信号。每天都有所有玩家共享的挑战。",flickCta:"了解 Flickerun 测试版",studioKicker:"PIXELRED STUDIO",studioTitle:"小型工作室。<br>耐玩的游戏。",studioText:"我们制作独立移动游戏，规则清晰、视觉鲜明，并以尊重玩家的方式设计成长体验。",studioCta:"聊聊游戏",studioAside:"反应力、记忆力，以及触手可及的下一局。",footerPrivacy:"隐私政策",footerLegal:"法律声明"}
};

const picker = document.getElementById("language");
const supported = Object.keys(copy);
const stored = localStorage.getItem("pixelred-language");
const browserLanguage = (navigator.language || "fr").slice(0,2).toLowerCase();
const initialLanguage = supported.includes(stored) ? stored : (supported.includes(browserLanguage) ? browserLanguage : "fr");

function setLanguage(language) {
  const messages = copy[language] || copy.fr;
  document.documentElement.lang = language;
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const value = messages[node.dataset.i18n];
    if (value !== undefined) node.innerHTML = value;
  });
  picker.value = language;
  localStorage.setItem("pixelred-language", language);
}

picker.addEventListener("change", () => setLanguage(picker.value));
document.getElementById("year").textContent = new Date().getFullYear();
setLanguage(initialLanguage);
